---@class DBCFCfgData
---@field public ID
---@field public LimitPhone
---@field public GridCity
---@field public GridWorld
---@field public TilesTotal
---@field public Minute2DiamRate
---@field public MaxTimeLen4ResYields
---@field public DepartCostResPerCell
---@field public FleetTimePerOnce
---@field public FleetMoveSpeed
---@field public FleetAtLeastSec